<a href="https://colab.research.google.com/github/abhishekanand04/DAV---Fundamentals/blob/fundamentals/Dec24_Chi_squared_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from scipy.stats import chisquare # Statistical test (chistat, pvalue)
from scipy.stats import chi2

You have a coin. You wish to ensure that it is fair.

You decide to toss it 50 times, and note the observations.

The observed outcomes from 50 coin tosses are 28 heads and 22 tails.

Determine if the coin is fair or biased.

In [ ]:
chi_stat, p_value = chisquare(
    [28, 22], # Observed or actual
    [25, 25], # Expected
)
print("p_value:",p_value)
print("chi_stat:",chi_stat)

p_value: 0.3961439091520741
chi_stat: 0.72

In [ ]:
alpha = 0.05

if p_value < alpha:
    print("Reject H0")
    print("Coin is baised")
else:
    print("Fail to reject H0")
    print("Coin is fair")

Fail to reject H0
Coin is fair

In [ ]:
#Using the formula
(28 - 25)**2 / 25 + (22 - 25)**2 / 25 # chi2stat

0.72

In [ ]:
1 - chi2.cdf(0.72, df=1)

0.3961439091520741

You decide to check if a different coin is fair or not, in similar way.

This time, the the observed outcomes from the 50 coin tosses are 45 heads and 5 tails.

Determine whether the coin is fair or biased.

In [ ]:
chi_stat, p_value = chisquare(
    [45, 5], # Observed or actual
    [25, 25], # Expected
)
print("p_value:",p_value)
print("chi_stat:",chi_stat)

p_value: 1.5417257900280013e-08
chi_stat: 32.0

In [ ]:
alpha = 0.05

if p_value < alpha:
    print("Reject H0")
    print("Coin is baised")
else:
    print("Fail to reject H0")
    print("Coin is fair")

Reject H0
Coin is baised

In [ ]:
(45 - 25)**2/25 + (5 - 25)**2 /25 # chi2stat

32.0

In [ ]:
1 - chi2.cdf(32, df=1)

1.5417257914762672e-08

In [ ]:
from scipy.stats import chi2_contingency

observed = [
    [527, 72],
    [206, 102],]

chi_stat, p_value, df, exp_freq = chi2_contingency(observed) # chi_stat, p_value, df, expected values
print("chi_stat:",chi_stat)
print("p_value:",p_value)
print("df:",df)
print("exp_freq:",exp_freq)

chi_stat: 57.04098674049609
p_value: 4.268230756875865e-14
df: 1
exp_freq: [[484.08710033 114.91289967]
 [248.91289967  59.08710033]]

In [ ]:
alpha = 0.05

if p_value < alpha:
    print("Reject H0")
    print("Gender and preference are not independent")
else:
    print("Fail to reject H0")
    print("Gender and preference are independent")

Reject H0
Gender and preference are not independent

In [ ]:
!wget --no-check-certificate https://drive.google.com/uc?id=12muEOrUvEtKAPVhKr4rSlrsqwjGuMJfu -O aerofit.csv

--2025-01-06 17:44:07--  https://drive.google.com/uc?id=12muEOrUvEtKAPVhKr4rSlrsqwjGuMJfu
Resolving drive.google.com (drive.google.com)... 142.250.101.101, 142.250.101.102, 142.250.101.139, ...
Connecting to drive.google.com (drive.google.com)|142.250.101.101|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=12muEOrUvEtKAPVhKr4rSlrsqwjGuMJfu [following]
--2025-01-06 17:44:08--  https://drive.usercontent.google.com/download?id=12muEOrUvEtKAPVhKr4rSlrsqwjGuMJfu
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.101.132, 2607:f8b0:4023:c06::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.101.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7461 (7.3K) [application/octet-stream]
Saving to: ‘aerofit.csv’

aerofit.csv         100%[===================>]   7.29K  --.-KB/s    in 0s

2025-01-06 17:44:10 (70.1 MB/s) - ‘aerofit.csv’ saved [7461/7461]

In [ ]:
df_aerofit = pd.read_csv('/content/aerofit.csv')

In [ ]:
df_aerofit.head()

  Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   KP281   18    Male         14        Single      3        4   29562    112
1   KP281   19    Male         15        Single      2        3   31836     75
2   KP281   19  Female         14     Partnered      4        3   30699     66
3   KP281   19    Male         12        Single      3        3   32973     85
4   KP281   20    Male         13     Partnered      4        2   35247     47

In [ ]:
# H0 = Gender does not impact the buying of product
# Ha = Gender impacts the buying of product

gender_product = pd.crosstab(index=df_aerofit['Gender'],columns=df_aerofit['Product'])
gender_product # This will give the count of each gender for each product

Product  KP281  KP481  KP781
Gender
Female      40     29      7
Male        40     31     33

In [ ]:
chi_stat, p_value, df, exp_freq = chi2_contingency(gender_product) # chi_stat, p_value, df, expected value

print("chi_stat:",chi_stat)
print("p_value:",p_value)
print("df:",df)
print("exp_freq:",exp_freq)

chi_stat: 12.923836032388664
p_value: 0.0015617972833158714
df: 2
exp_freq: [[33.77777778 25.33333333 16.88888889]
 [46.22222222 34.66666667 23.11111111]]

In [ ]:
alpha = 0.05

if p_value < alpha:
    print("Reject H0")
    print("Gender impacts product")
else:
    print("Fail to reject H0")
    print("Gender does not impact product")

Reject H0
Gender impacts product

In [ ]:
chi_stat, p_value, df, exp_freq = chi2_contingency([[40, 29], [40, 31]])

print("chi_stat:",chi_stat)
print("p_value:",p_value)
print("df:",df)
print("exp_freq:",exp_freq)

chi_stat: 0.0005953595971967067
p_value: 0.9805335549105975
df: 1
exp_freq: [[39.42857143 29.57142857]
 [40.57142857 30.42857143]]

In [ ]:
alpha = 0.05

if p_value < alpha:
    print("Reject H0")
    print("Gender impacts product")
else:
    print("Fail to reject H0")
    print("Gender does not impact product")

Fail to reject H0
Gender does not impact product